zuul:
#Service will be mapped under the /rest URI

 prefix: /api
 routes:
  hello-server:
   path: /server/**
   serviceId: HELLO-SERVER-SERVICE
  hello-client:
   path: /client/**
   serviceId: HELLO_CLIENTSERVICE

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/
  instance:
   hostname: localhost

server:
 port: 8079

spring:
 application:
  name: Zuul-Service

